/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ufc.poo.sorveteria.views;

import com.ufc.poo.sorveteria.services.ClienteService;
import com.ufc.poo.sorveteria.services.impl.ClienteServiceImpl;
import com.ufc.poo.sorveteria.model.Cliente;
import com.ufc.poo.sorveteria.repository.filter.ClienteFilter;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author mplma
 */
public class ClienteView extends javax.swing.JFrame {

    static void setVisivel(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Cliente
     */
    public ClienteView() {
        initComponents();
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jlbCliente = new javax.swing.JLabel();
        jBtnCadastroCliente = new javax.swing.JButton();
        jBtnVoltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTxtIdCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtNomeCliente = new javax.swing.JTextField();
        jBtnLimparFiltro = new javax.swing.JButton();
        jBtnFiltrarCliente = new javax.swing.JButton();
        jTxtCpfCliente = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCliente = new javax.swing.JTable();
        jBtnApagarCliente = new javax.swing.JButton();
        jBtnEditarCliente = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlbCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCliente.setText("CLIENTES");

        jBtnCadastroCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnCadastroCliente.setText("CADASTRAR CLIENTE");
        jBtnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadastroClienteActionPerformed(evt);
            }
        });

        jBtnVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnVoltar.setText("VOLTAR");
        jBtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVoltarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTxtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIdClienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NOME");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CPF");

        jTxtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeClienteActionPerformed(evt);
            }
        });

        jBtnLimparFiltro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnLimparFiltro.setText("LIMPAR");
        jBtnLimparFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparFiltroActionPerformed(evt);
            }
        });

        jBtnFiltrarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnFiltrarCliente.setText("FILTRAR CLIENTE");
        jBtnFiltrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFiltrarClienteActionPerformed(evt);
            }
        });

        try {
            jTxtCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156))
                            .addComponent(jTxtCpfCliente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnFiltrarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnLimparFiltro)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnLimparFiltro)
                    .addComponent(jBtnFiltrarCliente))
                .addGap(24, 24, 24))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("FILTRO CLIENTE");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("LISTA DE CLIENTES");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jtbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF", "TELEFONE", "DATA CRIACAO"
            }
        ));
        jScrollPane1.setViewportView(jtbCliente);

        jBtnApagarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnApagarCliente.setText("APAGAR");
        jBtnApagarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApagarClienteActionPerformed(evt);
            }
        });

        jBtnEditarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnEditarCliente.setText("EDITAR");
        jBtnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnEditarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnApagarCliente)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnApagarCliente)
                    .addComponent(jBtnEditarCliente))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBtnCadastroCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnVoltar))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jlbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnVoltar)
                    .addComponent(jBtnCadastroCliente))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadastroClienteActionPerformed
        AddCliente telaAddCliente = new AddCliente();
        telaAddCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnCadastroClienteActionPerformed
    
    private void initTable(){
        ClienteService service = new ClienteServiceImpl();
        List<Cliente> clientesEncontrados = service.buscar(null);
        preencherTable(clientesEncontrados);
    }
    
    private void preencherTable(List<Cliente> clientes){
        Vector<Vector<Object>> rows = new Vector();
        
        //criando as rows da tabela
        clientes.forEach(cliente -> {
            Vector<Object> row = new Vector();
            
            row.add(cliente.getId());
            row.add(cliente.getNome());
            row.add(cliente.getCpf());
            row.add(cliente.getTelefone());
            row.add(cliente.getCreatedAt());
            
            rows.add(row);
        });
        
        jtbCliente.setModel(new javax.swing.table.DefaultTableModel(
            rows,
            columnTable()
        ));
    }
    
    private Vector<String> columnTable(){
        Vector<String> column = new Vector();
        
        column.add("ID");
        column.add("Nome");
        column.add("CPF");
        column.add("Telefone");
        column.add("Criado em");
        return column;
    }
    
    private void jBtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVoltarActionPerformed
        new Principal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnVoltarActionPerformed

    private void jTxtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdClienteActionPerformed

    private void jTxtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeClienteActionPerformed

    private void jBtnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarClienteActionPerformed
        Integer linhaSelecionada = jtbCliente.getSelectedRow();
        if(linhaSelecionada != null){
            Cliente clienteSelecionado = new Cliente();
            clienteSelecionado.setId((Integer) jtbCliente.getValueAt(linhaSelecionada, 0));
            clienteSelecionado.setNome((String) jtbCliente.getValueAt(linhaSelecionada, 1));
            clienteSelecionado.setTelefone((String) jtbCliente.getValueAt(linhaSelecionada, 3));
            clienteSelecionado.setCpf((String) jtbCliente.getValueAt(linhaSelecionada, 2));      

            EdtCliente telaEdtCliente = new EdtCliente(clienteSelecionado);
            telaEdtCliente.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jBtnEditarClienteActionPerformed

    private void jBtnApagarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApagarClienteActionPerformed
         Integer linhaSelecionada = jtbCliente.getSelectedRow();
         if(linhaSelecionada != null){
             Integer idClienteSelecionado = (Integer) jtbCliente.getValueAt(linhaSelecionada, 0);
             
             ClienteService service = new ClienteServiceImpl();
             
             Integer escolha = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esse cliente?");
             
             if(escolha == 0){
                try{
                    removeLinha(linhaSelecionada);
                    
                    service.remover(idClienteSelecionado);
                    
                    JOptionPane.showMessageDialog(null, "Cliente removido com sucesso");
                    
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Não foi possível excluir cliente. Motivo: "+e.getMessage());
                }
             }
         }
    }//GEN-LAST:event_jBtnApagarClienteActionPerformed
    
    private void removeLinha(int linhaSelecionada){
        ((DefaultTableModel) jtbCliente.getModel()).removeRow(linhaSelecionada);
    }
        
    private void jBtnFiltrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFiltrarClienteActionPerformed
       ClienteService service = new ClienteServiceImpl();
       ClienteFilter filter = new ClienteFilter();
       filter.setId(jTxtIdCliente.getText().isEmpty() ? null : Integer.valueOf(jTxtIdCliente.getText().replaceAll("\\D", "")));
       filter.setCpf(jTxtCpfCliente.getText().isEmpty() ? null : jTxtCpfCliente.getText().replaceAll("\\D", ""));
       filter.setNome(jTxtNomeCliente.getText());
       
       List<Cliente> clientesEncontrados = service.buscar(filter);
       
       preencherTable(clientesEncontrados);
    }//GEN-LAST:event_jBtnFiltrarClienteActionPerformed

    private void jBtnLimparFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparFiltroActionPerformed
        jTxtIdCliente.setText("");
        jTxtCpfCliente.setText("");
        jTxtNomeCliente.setText("");
    }//GEN-LAST:event_jBtnLimparFiltroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApagarCliente;
    private javax.swing.JButton jBtnCadastroCliente;
    private javax.swing.JButton jBtnEditarCliente;
    private javax.swing.JButton jBtnFiltrarCliente;
    private javax.swing.JButton jBtnLimparFiltro;
    private javax.swing.JButton jBtnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JFormattedTextField jTxtCpfCliente;
    private javax.swing.JTextField jTxtIdCliente;
    private javax.swing.JTextField jTxtNomeCliente;
    private javax.swing.JLabel jlbCliente;
    private javax.swing.JTable jtbCliente;
    // End of variables declaration//GEN-END:variables
}
